kotlin.code.style=official

group = selab
version = 0.1

MAP = src/systemtest/resources/mapFiles/MapEmergencySimple.dot
ASSETS = src/systemtest/resources/assetsJsons/AssetsEmergencySimple.json
SCENARIO = src/systemtest/resources/scenarioJsons/ScenarioEmergencySimple.json
MAX_TICKS = 21

OUTPUT = /dev/stdout
