kotlin.code.style=official

group = selab
version = 0.1

MAP = src/systemtest/resources/testReallocation/map_reallocate.dot
ASSETS = src/systemtest/resources/testReallocation/assets_reallocate.json
SCENARIO = src/systemtest/resources/testReallocation/scenario.json
MAX_TICKS = 21

OUTPUT = /dev/stdout
