kotlin.code.style=official

group = selab
version = 0.1

MAP = src/systemtest/resources/AllocationWithEvent/map.dot
ASSETS = src/systemtest/resources/AllocationWithEvent/assets.json
SCENARIO = src/systemtest/resources/AllocationWithEvent/scenario.json
MAX_TICKS = 200
org.gradle.jvmargs=-Xmx4096m

OUTPUT = /dev/stdout
