package de.unisaarland.cs.se.selab

enum class LexerToken {
    ARROW,
    SEMICOLON,
    RPARENTHESES,
    LPARENTHESES,
    CLPARENTHESES,
    CRPARENTHESES,
    EQUAL,
    VILLAGE,
    NAME,
    HEIGHTLIMIT,
    WEIGHT,
    PRIMARYTYPE,
    SECONDARYTYPE,
    MAINSTREET,
    SIDESTREET,
    COUNTYROAD,
    ONEWAYSTREET,
    TUNNEL,
    NONE
}