package de.unisaarland.cs.se.selab.systemtest
import de.unisaarland.cs.se.selab.systemtest.basictests.EmergencySimpleTest
import de.unisaarland.cs.se.selab.systemtest.basictests.ExampleTest
import de.unisaarland.cs.se.selab.systemtest.basictests.Reallocation
import de.unisaarland.cs.se.selab.systemtest.basictests.ReroutingTest
import de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser1
import de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser18
import de.unisaarland.cs.se.selab.systemtest.failedmapparser.*
import de.unisaarland.cs.se.selab.systemtest.runner.SystemTestManager

object SystemTestRegistration {
    fun registerSystemTests(manager: SystemTestManager) {
        manager.registerTest(Reallocation())
        manager.registerTest(ExampleTest())
        manager.registerTest(EmergencySimpleTest())
        manager.registerTest(ReroutingTest())
        manager.registerTest(CountyRoadDifferentName())
        manager.registerTest(VehicleCapGRBaseCap())
        registerMapParserSyntaxFail1(manager)
        registerMapParserSyntaxFail2(manager)
        registerMapParserSemanticFail1(manager)
    }

    private fun registerMapParserSemanticFail1(manager: SystemTestManager) {
        manager.registerTest(FailedParser1())
        manager.registerTest(FailedParser2())
        manager.registerTest(FailedParser3())
        manager.registerTest(FailedParser4())
        manager.registerTest(FailedParser5())
        manager.registerTest(FailedParser6())
        manager.registerTest(FailedParser7())
        manager.registerTest(FailedParser8())
        manager.registerTest(FailedParser9())
        manager.registerTest(FailedParser10())
        manager.registerTest(FailedParser11())
        manager.registerTest(FailedParser12())
        manager.registerTest(FailedParser13())
        manager.registerTest(FailedParser14())
        manager.registerTest(FailedParser15())
        manager.registerTest(FailedParser16())
        manager.registerTest(FailedParser17())
    }

    private fun registerMapParserSyntaxFail1(manager: SystemTestManager) {
        manager.registerTest(FailedParserSyntax1())
        manager.registerTest(FailedParserSyntax2())
        manager.registerTest(FailedParserSyntax3())
        manager.registerTest(FailedParserSyntax4())
        manager.registerTest(FailedParserSyntax5())
        manager.registerTest(FailedParserSyntax6())
        manager.registerTest(FailedParserSyntax7())
        manager.registerTest(FailedParserSyntax8())
        manager.registerTest(FailedParserSyntax9())
        manager.registerTest(FailedParserSyntax10())
        manager.registerTest(FailedParserSyntax11())
        manager.registerTest(FailedParserSyntax12())
        manager.registerTest(FailedParserSyntax13())
        manager.registerTest(FailedParserSyntax14())
        manager.registerTest(FailedParserSyntax15())
        manager.registerTest(FailedParserSyntax16())
        manager.registerTest(FailedParserSyntax17())
        manager.registerTest(FailedParserSyntax18())
        manager.registerTest(FailedParserSyntax19())
        manager.registerTest(FailedParserSyntax20())
        manager.registerTest(FailedParserSyntax21())
        manager.registerTest(FailedParserSyntax22())
        manager.registerTest(FailedParserSyntax23())
        manager.registerTest(FailedParserSyntax24())
        manager.registerTest(FailedParserSyntax25())
        manager.registerTest(FailedParserSyntax26())
        manager.registerTest(FailedParserSyntax27())
        manager.registerTest(FailedParserSyntax28())
        manager.registerTest(FailedParserSyntax29())
        manager.registerTest(FailedParserSyntax30())
        manager.registerTest(FailedParserSyntax31())
        manager.registerTest(FailedParserSyntax32())
        manager.registerTest(FailedParserSyntax33())
        manager.registerTest(FailedParserSyntax34())
        manager.registerTest(FailedParserSyntax35())
        manager.registerTest(FailedParserSyntax36())
    }

    private fun registerMapParserSyntaxFail2(manager: SystemTestManager) {
        manager.registerTest(FailedParserSyntax37())
        manager.registerTest(FailedParserSyntax38())
        manager.registerTest(FailedParserSyntax39())
        manager.registerTest(FailedParserSyntax40())
        manager.registerTest(FailedParserSyntax41())
        manager.registerTest(FailedParserSyntax42())
        manager.registerTest(FailedParserSyntax43())
        manager.registerTest(FailedParserSyntax44())
        manager.registerTest(FailedParserSyntax45())
        manager.registerTest(FailedParserSyntax46())
        manager.registerTest(FailedParserSyntax47())
        manager.registerTest(FailedParserSyntax48())
        manager.registerTest(FailedParserSyntax49())
        manager.registerTest(FailedParserSyntax50())
        manager.registerTest(FailedParserSyntax51())
        manager.registerTest(FailedParserSyntax52())
        manager.registerTest(FailedParserSyntax53())
        manager.registerTest(FailedParserSyntax54())
        manager.registerTest(FailedParserSyntax55())
        manager.registerTest(FailedParserSyntax56())
        manager.registerTest(FailedParserSyntax57())
        manager.registerTest(FailedParserSyntax58())
        manager.registerTest(FailedParserSyntax59())
        manager.registerTest(FailedParserSyntax60())
        manager.registerTest(FailedParserSyntax61())
        manager.registerTest(FailedParserSyntax62())
        manager.registerTest(FailedParserSyntax63())
        manager.registerTest(FailedParserSyntax64())
        manager.registerTest(FailedParserSyntax65())
        manager.registerTest(FailedParserSyntax66())
        manager.registerTest(FailedParserSyntax67())
        manager.registerTest(FailedParserSyntax68())
        manager.registerTest(FailedParserSyntax69())
        manager.registerTest(FailedParserSyntax70())
        manager.registerTest(FailedParserSyntax71())
        manager.registerTest(FailedParserSyntax72())
        manager.registerTest(FailedParserSyntax73())
        manager.registerTest(FailedParserSyntax74())
        manager.registerTest(FailedParserSyntax75())
        manager.registerTest(FailedParserSyntax76())
        manager.registerTest(FailedParserSyntax77())
        manager.registerTest(FailedParserSyntax78())
    }

    fun config2(manager:SystemTestManager) {
        manager.registerTest(FailedParser1())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser2())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser3())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser4())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser5())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser6())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser7())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser8())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser9())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser10())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser11())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser12())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser13())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser14())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser15())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser16())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser17())
        manager.registerTest(FailedParser18())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser19())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser20())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser21())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser22())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser23())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser24())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser25())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser26())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser27())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser28())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser29())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser30())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser31())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser32())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser33())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser34())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser35())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser36())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser37())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser38())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser39())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser40())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser41())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser42())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser43())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser44())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser45())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser46())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser47())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser48())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser49())
        manager.registerTest(de.unisaarland.cs.se.selab.systemtest.failedconfig2parser.FailedParser50())
    }
}
